<a href="https://colab.research.google.com/github/Tienspkt/google-colab/blob/main/baitap01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data.head(20)
data[data['NOC']== 'BEL']

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
3,1924,Chamonix,Bobsleigh,Bobsleigh,BEL,four-man,M,Bronze
53,1928,St. Moritz,Skating,Figure skating,BEL,individual,M,Bronze
191,1948,St. Moritz,Bobsleigh,Bobsleigh,BEL,four-man,M,Silver
192,1948,St. Moritz,Skating,Figure skating,BEL,pairs,X,Gold
1638,1998,Nagano,Skating,Speed skating,BEL,5000m,M,Bronze

In [2]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data.head(20)
data[data['NOC']== 'CAN'] #lấy dữ liệu cửa nước canada

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
54,1928,St. Moritz,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
92,1932,Lake Placid,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
93,1932,Lake Placid,Skating,Figure skating,CAN,individual,M,Bronze
94,1932,Lake Placid,Skating,Speed skating,CAN,10000m,M,Bronze
...,...,...,...,...,...,...,...,...
2105,2006,Turin,Skating,Speed skating,CAN,Team pursuit,W,Silver
2106,2006,Turin,Skiing,Cross Country S,CAN,Sprint 1.5km,W,Gold
2107,2006,Turin,Skiing,Cross Country S,CAN,Team sprint,W,Silver
2108,2006,Turin,Skiing,Freestyle Ski.,CAN,moguls,W,Gold
2109,2006,Turin,Skiing,Snowboard,CAN,Snowboard Cross,W,Bronze

In [18]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data['NOC'].max() #nước có huy chương nhiểu nhất

'YUG'

In [27]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data['NOC'].min() #nước có huy chương nhiểu nhất

'AUS'

In [30]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data[(data['NOC']=='CAN') & (data['Year']==2006)]

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
2086,2006,Turin,Bobsleigh,Bobsleigh,CAN,two-man,M,Silver
2087,2006,Turin,Bobsleigh,Skeleton,CAN,individual,M,Gold
2088,2006,Turin,Bobsleigh,Skeleton,CAN,individual,M,Silver
2089,2006,Turin,Bobsleigh,Skeleton,CAN,individual,W,Bronze
2090,2006,Turin,Curling,Curling,CAN,curling,M,Gold
2091,2006,Turin,Curling,Curling,CAN,curling,W,Bronze
2092,2006,Turin,Ice Hockey,Ice Hockey,CAN,ice hockey,W,Gold
2093,2006,Turin,Skating,Figure skating,CAN,individual,M,Bronze
2094,2006,Turin,Skating,Short Track S.,CAN,3000m relay,W,Silver
2095,2006,Turin,Skating,Short Track S.,CAN,5000m relay,M,Silver
2096,2006,Turin,Skating,Short Track S.,CAN,500m,M,Silver
2097,2006,Turin,Skating,Short Track S.,CAN,500m,W,Bronze
2098,2006,Turin,Skating,Speed skating,CAN,1000m,W,Silver
2099,2006,Turin,Skating,Speed skating,CAN,1500m,W,Gold
2100,2006,Turin,Skating,Speed skating,CAN,1500m,W,Silver
2101,2006,Turin,Skating,Speed skating,CAN,3000m,W,Bronze
2102,2006,Turin,Skating,Speed skating,CAN,5000m,W,Bronze
2103,2006,Turin,Skating,Speed skating,CAN,5000m,W,Gold
2104,2006,Turin,Skating,Speed skating,CAN,Team pursuit,M,Silver
2105,2006,Turin,Skating,Speed skating,CAN,Team pursuit,W,Silver
2106,2006,Turin,Skiing,Cross Country S,CAN,Sprint 1.5km,W,Gold
2107,2006,Turin,Skiing,Cross Country S,CAN,Team sprint,W,Silver
2108,2006,Turin,Skiing,Freestyle Ski.,CAN,moguls,W,Gold
2109,2006,Turin,Skiing,Snowboard,CAN,Snowboard Cross,W,Bronze

In [16]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data[data['NOC']== 'CAN'] #lấy dữ liệu nước canada
data[(data['NOC']=='CAN')&(data['Medal']=='Gold')] # lấy huy chương vàng của tất cả các năm của nước CANADA

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
54,1928,St. Moritz,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
92,1932,Lake Placid,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
193,1948,St. Moritz,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
194,1948,St. Moritz,Skating,Figure skating,CAN,individual,W,Gold
259,1952,Oslo,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
398,1960,Squaw Valley,Skating,Figure skating,CAN,pairs,X,Gold
399,1960,Squaw Valley,Skiing,Alpine Skiing,CAN,slalom,W,Gold
483,1964,Innsbruck,Bobsleigh,Bobsleigh,CAN,four-man,M,Gold
586,1968,Grenoble,Skiing,Alpine Skiing,CAN,giant slalom,W,Gold
793,1976,Innsbruck,Skiing,Alpine Skiing,CAN,giant slalom,W,Gold
1013,1984,Sarajevo,Skating,Speed skating,CAN,1000m,M,Gold
1014,1984,Sarajevo,Skating,Speed skating,CAN,1500m,M,Gold
1291,1992,Albertville,Skating,Short Track S.,CAN,3000m relay,W,Gold
1293,1992,Albertville,Skiing,Alpine Skiing,CAN,downhill,W,Gold
1449,1994,Lillehammer,Biathlon,Biathlon,CAN,15km,W,Gold
1450,1994,Lillehammer,Biathlon,Biathlon,CAN,7.5km,W,Gold
1461,1994,Lillehammer,Skiing,Freestyle Ski.,CAN,moguls,M,Gold
1642,1998,Nagano,Bobsleigh,Bobsleigh,CAN,two-man,M,Gold
1644,1998,Nagano,Curling,Curling,CAN,curling,W,Gold
1649,1998,Nagano,Skating,Short Track S.,CAN,5000m relay,M,Gold
1650,1998,Nagano,Skating,Short Track S.,CAN,500m,W,Gold
1654,1998,Nagano,Skating,Speed skating,CAN,500m,W,Gold
1656,1998,Nagano,Skiing,Snowboard,CAN,giant-slalom,M,Gold
1850,2002,Salt Lake City,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
1851,2002,Salt Lake City,Ice Hockey,Ice Hockey,CAN,ice hockey,W,Gold
1852,2002,Salt Lake City,Skating,Figure skating,CAN,pairs,X,Gold
1856,2002,Salt Lake City,Skating,Short Track S.,CAN,5000m relay,M,Gold
1857,2002,Salt Lake City,Skating,Short Track S.,CAN,500m,M,Gold
1861,2002,Salt Lake City,Skating,Speed skating,CAN,500m,W,Gold
1862,2002,Salt Lake City,Skiing,Cross Country S,CAN,5km pursuit,W,Gold
2087,2006,Turin,Bobsleigh,Skeleton,CAN,individual,M,Gold
2090,2006,Turin,Curling,Curling,CAN,curling,M,Gold
2092,2006,Turin,Ice Hockey,Ice Hockey,CAN,ice hockey,W,Gold
2099,2006,Turin,Skating,Speed skating,CAN,1500m,W,Gold
2103,2006,Turin,Skating,Speed skating,CAN,5000m,W,Gold
2106,2006,Turin,Skiing,Cross Country S,CAN,Sprint 1.5km,W,Gold
2108,2006,Turin,Skiing,Freestyle Ski.,CAN,moguls,W,Gold

In [15]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data[data['NOC']== 'CAN'] #lấy dữ liệu nước canada
data[(data['NOC']=='CAN')&(data['Year']==2006)&(data['Medal']=='Gold')]#số huy chương vàng nước canada đạt được năm 2006

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
2087,2006,Turin,Bobsleigh,Skeleton,CAN,individual,M,Gold
2090,2006,Turin,Curling,Curling,CAN,curling,M,Gold
2092,2006,Turin,Ice Hockey,Ice Hockey,CAN,ice hockey,W,Gold
2099,2006,Turin,Skating,Speed skating,CAN,1500m,W,Gold
2103,2006,Turin,Skating,Speed skating,CAN,5000m,W,Gold
2106,2006,Turin,Skiing,Cross Country S,CAN,Sprint 1.5km,W,Gold
2108,2006,Turin,Skiing,Freestyle Ski.,CAN,moguls,W,Gold

In [26]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data[(data['NOC']=='CAN')&(data['Medal'].count())]

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
54,1928,St. Moritz,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
92,1932,Lake Placid,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
93,1932,Lake Placid,Skating,Figure skating,CAN,individual,M,Bronze
94,1932,Lake Placid,Skating,Speed skating,CAN,10000m,M,Bronze
...,...,...,...,...,...,...,...,...
2105,2006,Turin,Skating,Speed skating,CAN,Team pursuit,W,Silver
2106,2006,Turin,Skiing,Cross Country S,CAN,Sprint 1.5km,W,Gold
2107,2006,Turin,Skiing,Cross Country S,CAN,Team sprint,W,Silver
2108,2006,Turin,Skiing,Freestyle Ski.,CAN,moguls,W,Gold
2109,2006,Turin,Skiing,Snowboard,CAN,Snowboard Cross,W,Bronze

In [19]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data[data['NOC']== 'CAN'] #lấy dữ liệu nước canada
data['Medal'].value_counts()   #đếm số huy chương vàng bạc đồng trong cột huy chương của toàn bộ  dữ liệu

Gold      774
Silver    773
Bronze    764
Name: Medal, dtype: int64

In [21]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data.groupby((data['NOC']=='CAN')&(data['Year']==2006)&(data['Medal']=='Gold')).count()      #đếm số huy chương vàng năm 2006 của canada

       Year  City  Sport  Discipline   NOC  Event  Event gender  Medal
False  2304  2304   2304        2304  2304   2304          2304   2304
True      7     7      7           7     7      7             7      7

In [23]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data.groupby((data['NOC']=='CAN')&(data['Year']==2006)&(data['Medal']=='Silver')).count()    #đếm số huy chương bạc năm 2006 của canada

       Year  City  Sport  Discipline   NOC  Event  Event gender  Medal
False  2301  2301   2301        2301  2301   2301          2301   2301
True     10    10     10          10    10     10            10     10

In [24]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data.groupby((data['NOC']=='CAN')&(data['Year']==2006)&(data['Medal']=='Bronze')).count()    #đếm số huy chương đồng năm 2006 của canada

       Year  City  Sport  Discipline   NOC  Event  Event gender  Medal
False  2304  2304   2304        2304  2304   2304          2304   2304
True      7     7      7           7     7      7             7      7

In [25]:
import pandas as pd
url = 'http://Winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data.groupby((data['NOC']=='CAN')&(data['Year']==2006)&data['Medal']).count()

       Year  City  Sport  Discipline   NOC  Event  Event gender  Medal
False  2287  2287   2287        2287  2287   2287          2287   2287
True     24    24     24          24    24     24            24     24